version: '3.8'

services:
  ezfile:
    build:
      context: .
      args:
        URL_BASE_PATH: ${URL_BASE_PATH:-}
    container_name: ezfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - BASE_PATH=/app/storage
      - DOMAIN=${DOMAIN:-localhost:3000}
    volumes:
      - ./storage:/app/storage
      - ./dev.db:/app/prisma/dev.db
