version: '3.8'

services:
  ezfile:
    # Verwende 'latest' für stabile Releases, oder 'dev' für aktuelle Entwicklungsversionen
    image: ghcr.io/yezun-hikari/ezfile:dev
    container_name: ezfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - BASE_PATH=/app/storage
      - DOMAIN=${DOMAIN:-localhost:3000}
      - URL_BASE_PATH=${URL_BASE_PATH:-}
      - DATABASE_URL=file:/app/storage/dev.db
    volumes:
      - ./storage:/app/storage
